### PR TITLE
Browser Interaction

### PR DESCRIPTION
**Pull request by mariocraft987**
I added 2 very useful blocks

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
You shouldn't be deleting old extensions. You could just edit the existing one since it already has those blocks.

**Comment by mariocraft987** [comment]
....

**Comment by jwklong** [comment]
you still deleted a entire extension bro

**Comment by SharkPool-SP** [comment]
the majority of these blocks are just copies from Randomlyblocks, the classes are still the same, and some of these blocks have nothing to do with interacting with the browser.

Im closing this.

**Comment by mariocraft987** [comment]
Thank you sir, for making me win my friend's bet

**Comment by CodeFoxy-Github** [comment]
???

> Thank you sir, for making me win my friend's bet

**Comment by CodeFoxy-Github** [comment]
**So tf is this**

**Comment by mariocraft987** [comment]
> **So tf is this**

A bet☠️☠️☠️☠️☠️

**Comment by CodeFoxy-Github** [comment]
Bruhh

**Comment by SharkPool-SP** [comment]
You do realize this makes us not want to merge anything from you right

**Pull request closed without merging**
