### PR TITLE
Create workingturbogpt.js

### PR DESCRIPTION
**Pull request by Anonymous-cat1**
Description:
Harness the power of ChatGPT-3.5 in your projects! (for free!)

Thumbnail:
image

Repo:
https://github.com/Anonymous-cat1/WorkingTurboGPT

ID: workingturboGPT

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
why are some errors returned as "Error:", other errors are thrown, and some errors are only logged in console.error?
ideally either all errors should be either logged & returned or logged & thrown

**Comment by Themeetly2** [comment]
imagine not getting your extension in turbowarp 💀

**Comment by Anonymous-cat1** [comment]
> why are some errors returned as "Error:", other errors are thrown, and some errors are only logged in console.error? ideally either all errors should be either logged & returned or logged & thrown

I dunno man 😭

**Comment by JeremyGamer13** [comment]
seeing as the fix isnt that hard, i might merge this in a bit & fix it myself if you dont know

**Comment by Anonymous-cat1** [comment]
> seeing as the fix isnt that hard, i might merge this in a bit & fix it myself if you dont know

That would be appreciated, I've been told there's an issue the "lastGeneration" block as it always reports "That chatbot does not exist." and I don't know how to fix that either. (you can probably tell the extension is held together with office tape and school glue)

**Comment by Anonymous-cat1** [comment]
> > seeing as the fix isnt that hard, i might merge this in a bit & fix it myself if you dont know
> 
> That would be appreciated, I've been told there's an issue the "lastGeneration" block as it always reports "That chatbot does not exist." and I don't know how to fix that either. (you can probably tell the extension is held together with office tape and school glue)

Also, I remember you asking me to get permission from LOLEMO to merge the extension. I _not_ sure how to do that. (or how it will go) I'm sure it's fine since both extensions are licensed under the MIT license (but what do I know)

**Comment by JeremyGamer13** [comment]
it is legally fine it seems, but i would like it if they knew that their extension was gonna be added and were able to decide

**Comment by Anonymous-cat1** [comment]
I honestly have no idea now, LOLEMO had discontinued TurboGPT (probably
because of WorkingTurboGPT, I feel bad about that)

**Comment by JeremyGamer13** [comment]
the default & only mentioned api url now blocks penguinmod, will convert to draft
i think now its been long enough to merge this if another url is found & lolemo has no plans with turbogpt anymore
sorry for taking a while, lot of things to do & was waiting for permission just incase

**Pull request closed without merging**
