### PR TITLE
Update Box2D.js (sliders and performance)

### PR DESCRIPTION
**Pull request by pooiod**
I added controls for physics iterations and performance. I also added a new joint type: Slider
I also propose that the image be updated to this:
Box2D extension banner

### CODE REVIEW

**Comment by pooiod** [comment]
E

**Comment by RedMan13** [comment]
oh yeah you can update the image yourself in this commit, you don't need us to do it

**Comment by JeremyGamer13** [comment]
ima doo it anyways

**Review by JeremyGamer13 — CHANGES_REQUESTED** [review]

**Comment by RedMan13** [comment]
> ima doo it anywa

bouce

**Comment by pooiod** [comment]
I fixed the things

**Review by JeremyGamer13 — APPROVED** [review]

**Pull request merged**
