### PR TITLE
Leap Year/Unix Time Stamp Extension

### PR DESCRIPTION
**Pull request by nmsderp**
small extension that adds a leap year block, some unix timestamp stuff, and a millisecond converter

### CODE REVIEW

**Comment by RedMan13** [comment]
erm actually the syntax is correct *but* it is just a turbobuoder or whatever it's called extension

**Comment by Mariocraft987** [comment]
intresting... I'll maybe add it to my fork

**Comment by RedMan13** [comment]
I added the unix block to pm when you made this pr cause I liked the idea ad stole it :trollface:

**Comment by Mariocraft987** [comment]
Hehe :trollface::trollface:

**Comment by nmsderp** [comment]
> I added the unix block to pm when you made this pr cause I liked the idea ad stole it :trollface:

cool

**Pull request closed without merging**
