### PR TITLE
gtoolbox submission

### PR DESCRIPTION
**Pull request by meysam-iran**

### CODE REVIEW

**Comment by derpygamer2142** [comment]
most of these exist in other extensions

**Comment by meysam-iran** [comment]
well, those where the only blocks in turbobuilder, and im not a master at javascript so, yeah its very boring, and those sound functions where the part of turbobuilders code because of the sound block, those sound code are recommended to ignore, infact try making a extension in turbobuilder, you will see the sound code there

**Comment by meysam-iran** [comment]
and btw, i live in iran, thats why i wont reply when you are awake, if you are wondering

**Comment by RedMan13** [comment]
i see no reason for this to be on the main gallery

**Comment by meysam-iran** [comment]
yeah youre right, throw it in the trash bin

**Comment by RedMan13** [comment]
boowompwomp

**Pull request closed without merging**
