### PR TITLE
Added PenguinLlama.js

### PR DESCRIPTION
**Pull request by Gamma7113131**

### CODE REVIEW

**Comment by hammouda101010** [comment]
this... is just one block.

**Comment by RedMan13** [comment]
yeah wth xd

**Comment by JeremyGamer13** [comment]
the apis this extension uses dont seem very stable (a free python api accessed through a public request proxy)

**Comment by derpygamer2142** [comment]
penguinai already has this model

**Comment by Gamma7113131** [comment]
> penguinai already has this model

Ok

**Comment by Gamma7113131** [comment]
> the apis this extension uses dont seem very stable (a free python api accessed through a public request proxy)

Ok

**Comment by Gamma7113131** [comment]
> this... is just one block.

-_-

**Pull request closed without merging**
