### PR TITLE
V1.9 | PenguinGPT Update

### PR DESCRIPTION
**Pull request by cicerorph**
New features:

> Vision (Make AI see images, only works from gpt-4 and up)
> Claude 3 and LLama support and more models

New blocks:

> Get current model
> Attach image () to next message

### CODE REVIEW

**Comment by RedMan13** [comment]
and mis was tested and works?

**Comment by cicerorph** [comment]
yes


> and this was tested and works?

**Comment by RedMan13** [comment]
small stylistic issue: labels do not need (and should not have) opcodes on them

**Comment by RedMan13** [comment]
opps forgot to mergeg :trollface:

**Comment by cicerorph** [comment]
Please, before saying it's not working, verify why its not on the Discord Server of PenguinMod.
The reason why it's not working, its because im rewritting the entirety of the API of PenguinGPT, so please wait.

**Comment by PuzzlingGGG** [comment]
maybe make the blocks temporarily say that it's down for maintenance

**Comment by RedMan13** [comment]
make a stand in server that actually serves an error message to the requestomg client instead of using error server does not exist

**Comment by cicerorph** [comment]
> make a stand in server that actually serves an error message to the requesting client instead of using error server does not exist

Yea i was planning to do that long ago but im so busy i cant do that rn

**Pull request merged**
