### PR TITLE
New extension added! 🗂️

### PR DESCRIPTION
**Pull request by A1fasaop**
I made an extension called "What is the best mod"!

Here is the code of the extension.
Screenshot_2024-02-12-17-25-50-594_com android chrome

### CODE REVIEW

**Comment by RedMan13** [comment]
why is the png file a data uri of a png file, just upload the png file

**Comment by RedMan13** [comment]
also, please read the guide, none of the added files appear to be where they should be

**Comment by RedMan13** [comment]
nvm, but still, nothing should be outside the source folders

**Comment by A1fasaop** [comment]
I fixed it now!

**Comment by RedMan13** [comment]
i think you forgor to commit? cause nothing has changed

**Comment by A1fasaop** [comment]
.......

**Comment by RedMan13** [comment]
nothing has changed steel

**Comment by A1fasaop** [comment]
I'm going to fix this in a few minutes.....

**Comment by A1fasaop** [comment]
Go to What_is_the_best_mod.jpg file.

**Comment by A1fasaop** [comment]
This is my first extension ever made!

**Comment by A1fasaop** [comment]
Here's my extension blocks.
Screenshot_2024-02-11-18-01-24-611_com android chrome

**Comment by A1fasaop** [comment]
Ok!

**Comment by A1fasaop** [comment]
My dream is to publish an extension!

**Comment by A1fasaop** [comment]
Ask JeremyGamer13 to add my extension!

**Comment by A1fasaop** [comment]
LOL!!!

**Comment by A1fasaop** [comment]
Jeremy got online!!!!
Everyone be turned!!!!!!

**Comment by RedMan13** [comment]
your in the discord?

**Comment by A1fasaop** [comment]
No!

**Comment by RedMan13** [comment]
o

**Comment by JeremyGamer13** [comment]
this unfortunately doesnt seem to have a good use-case, not sure about merging it

**Comment by A1fasaop** [comment]
> this unfortunately doesnt seem to have a good use-case, not sure about merging it

Nooooooooooooooooooooooooooooooooooooooo!!!!!!!!!! ༼⁠;⁠´⁠༎ຶ⁠ ⁠۝ ⁠༎ຶ⁠༽

**Comment by A1fasaop** [comment]
> this unfortunately doesnt seem to have a good use-case, not sure about merging it

Oh God, if only the extension will be published

**Comment by RedMan13** [comment]
nah

**Comment by PuzzlingGGG** [comment]
this extension has literally no use.. its just a reporter that reports “PenguinMod” that has no use. At all. if you just want penguinmod text use the join block like “join “Penguin” “Mod”” i mean there’s no real reason or use for this..

**Comment by SharkPool-SP** [comment]
> this extension has literally no use.. its just a reporter that reports “PenguinMod” that has no use. At all. if you just want penguinmod text use the join block like “join “Penguin” “Mod”” i mean there’s no real reason or use for this..

Facts

**Comment by A1fasaop** [comment]
But still, it's my first extension ever, and  I only started JavaScript!

**Comment by A1fasaop** [comment]
(⁠༎ຶ⁠ ⁠෴⁠ ⁠༎ຶ⁠)

**Comment by JeremyGamer13** [comment]
closed because of general responses by other people that i was basing my option on since i didnt know 🤷‍♂️

**Comment by A1fasaop** [comment]
Oooooooooofffffffffffffffff

вс, 10 мар. 2024 г., 10:34 JeremyGamer13 ***@***.***>:

**Pull request closed without merging**
