### PR TITLE
add funny image blocks pls

### PR DESCRIPTION
**Pull request by Ashimee**
funne image blocks
image
idk why i want to add it other than its funne

### CODE REVIEW

**Comment by nmsderp** [comment]
best extension

**Comment by derpygamer2142** [comment]
amazing, please merge

**Comment by JeremyGamer13** [comment]
very silly but unfortunately it is too silly
- you should add a label or button that states that image blocks will only appear once placed on the workspace
- monitors are not disabled properly on the blocks (use `disableMonitor: true`)
- remove your name from the extension name since its just too big in the sidebar list (add it as a seperate label if you really want it, but extension listings on the site will include the author's name & link)
- images should be loaded from a trusted source since some of them just dont load at all (you could even host these on extensions.penguinmod.com itself if you add the files to the `static` folder in the repository)
- the mr beast video plays audio uncontrollably (best solution would be to just mute it)
- the troll face is too big make him smaller (:trollface:)

**Comment by fo-od** [comment]
it would be cool if you could do custom ones too
and also possibly useful

**Comment by Ashimee** [comment]
no its to much of a hassle
________________________________

**Comment by JeremyGamer13** [comment]
will merge this soon 👌

**Comment by JeremyGamer13** [comment]
needs some small edits so thats why im gonna look at something first

**Pull request merged**
