### PR TITLE
Add Git Penguin extension

### PR DESCRIPTION
**Pull request by JustablockCode**
I made pull req to add my extension to gallery:))

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
Ill fix the other minor formatting stuff, just fix those things first. You also might wanna make the block color ligher cuz of dark mode, idk

**Comment by JustablockCode** [comment]
> Ill fix the other minor formatting stuff, just fix those things first. You also might wanna make the block color ligher cuz of dark mode, idk

I think I need to change logo cus it won't fit 😭

**Comment by Mariocraft987** [comment]
That seems like a vary dangerous extension, as it could probably create chaos in github respitorys

**Comment by RedMan13** [comment]
> That seems like a vary dangerous extension, as it could probably create chaos in github respitorys

except, you already can

**Comment by Mariocraft987** [comment]
It can change or delete respitorys :shudders:

**Comment by RedMan13** [comment]
> It can change or delete respitorys :shudders:

no it cant, there arnt any blocks to do that in this extension. and i ask you yet again, you do realize you cant just *do* that right?

**Comment by Mariocraft987** [comment]
no... idk

**Comment by RedMan13** [comment]
:gasp

**Comment by JustablockCode** [comment]
so umm... r u going to add it?

**Comment by SharkPool-SP** [comment]
> so umm... r u going to add it?

you didnt fix the stuff I told you to, so no

**Comment by JeremyGamer13** [comment]
all of the things that were marked as resolved, are not actually resolved

**Comment by TheShovel** [comment]
what conflicts do you have????

**Comment by TheShovel** [comment]
finally

**Pull request merged**
