### PR TITLE
Change Discord Auth

### PR DESCRIPTION
**Pull request by cicerorph**

### CODE REVIEW

**Comment by cicerorph** [comment]
Yes i know i just changed the banner and icons of the extension, i will add more features when i can.

**Comment by cicerorph** [comment]
image

**Comment by cicerorph** [comment]
to be honest don't even use those images, i will probably use it in a extension of mine

**Comment by CodeFoxy-Github** [comment]
E

**Comment by CodeFoxy-Github** [comment]
e

Cicero ***@***.***> 於 2024年9月21日 週六 上午1:22寫道：

**Pull request closed without merging**
