### PR TITLE
Create FaviconUltilities.js

### PR DESCRIPTION
**Pull request by Noahcatz**

### CODE REVIEW

**Comment by CodeFoxy-Github** [comment]
? what is this

**Comment by CodeFoxy-Github** [comment]
variables["honk2"] this can be easy hacked.

**Comment by RedMan13** [comment]
> variables["honk2"] this can be easy hacked.

just like idk, literally everything 🥱

**Comment by Noahcatz** [comment]
Sorry I’m new to this idk what I’m even doing 😭
Sent from my iPhone

On Aug 26, 2024, at 12:50 PM, godslayerakp ***@***.***> wrote:

﻿

variables["honk2"] this can be easy hacked.

just like idk, literally everything 🥱

**Comment by CodeFoxy-Github** [comment]
Bruh

Noahcatz ***@***.***>於 2024年8月27日 週二，上午3:05寫道：

> Sorry I’m new to this idk what I’m even doing 😭
> Sent from my iPhone
>

**Comment by CodeFoxy-Github** [comment]
I think this is probably make on turbo builder cuz why (
doSound)

**Pull request closed without merging**
