### PR TITLE
add OOP to More Types extension

### PR DESCRIPTION
**Pull request by lego7set**
uhhh i saw the OOP extension from live tests and decided to reimplement it in more types.

this update adds classes, methods, this, instanceof block and a version of the for key value block for tempVars (cuz scratch variables boring)

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
does this also fix the bug where the project doesnt save with the blocks

**Comment by lego7set** [comment]
what do you mean? do the blocks disappear when the project is saved?

**Comment by lego7set** [comment]
or are you talking about the fact that the new values from this extension aren't saved?

**Comment by JeremyGamer13** [comment]
i shouldve worded that better
basically the project just cant save if a variable is set to a map for example
image

**Comment by lego7set** [comment]
huh? i dont see this happening?

**Comment by lego7set** [comment]
is this an uploaded project? cuz i havent tested that

**Comment by JeremyGamer13** [comment]
oh this seems to be fixed in the changes you made, sorry if i didnt make it clear

**Comment by lego7set** [comment]
:ok:

**Comment by JeremyGamer13** [comment]
this seems good to merge although we are getting to the point where its difficult for me to tell how to even test this extension :skull:

**Pull request merged**
