### PR TITLE
Add Sprite Effects (More Canvas Effects too)

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Introducing Sprite Effects
This extension adds many new visual effects that can be applied to the Sprite and THE CANVAS!
Ever wanted to put fisheye on the canvas? Maybe even a ripple effect? Maybe BOTH? Well, this extension does it for you...

This is WAY faster than Image Effects, supports custom svg filters, and more!!!

image

### CODE REVIEW

**Comment by TheShovel** [comment]
Screenshot_20231206_215042
You gotta adjust the viewbox to compensate for effects. Making people add a invisible box themselves won't do.

**Comment by SharkPool-SP** [comment]
> Screenshot_20231206_215042 You gotta adjust the viewbox to compensate for effects. Making people add a invisible box themselves won't do.

Fixed:
image
image

**Comment by TheShovel** [comment]
It seems to work fine. Is this ready to merge?

**Comment by SharkPool-SP** [comment]
> It seems to work fine. Is this ready to merge? Resolve the conflicts by the way.

fixed

**Comment by TheShovel** [comment]
You seem to still be making commits. Tell me when it's ready to merge :)

**Comment by RedMan13** [comment]
i do not know why this is still siting here

**Comment by RedMan13** [comment]
> > You seem to still be making commits. Tell me when it's ready to merge :)
> 
> It's ready now, just needed to fix a small bug and tell GitHub to stop complaining about conflicts :trollface:

bug?
also github stoped complaining about any conflicts a while ago it seems

**Comment by SharkPool-SP** [comment]
> > > You seem to still be making commits. Tell me when it's ready to merge :)
> 
> > 
> 
> > It's ready now, just needed to fix a small bug and tell GitHub to stop complaining about conflicts :trollface:
> 
> 
> 
> bug?
> 
> also github stoped complaining about any conflicts a while ago it seems

Ye I fixed it yesterday. The bug was a small canvas effect one, where fullscreen cut off the certain effects. It's fixed now :D

**Comment by RedMan13** [comment]
pog

**Comment by TheShovel** [comment]
> i do not know why this is still siting here

I wanted to merge it >:(

**Comment by SharkPool-SP** [comment]
> > i do not know why this is still siting here
> 
> 
> 
> I wanted to merge it >:(

I'm gonna need you to merge a new thumbnail in a sec so uh ye

**Pull request merged**
