### PR TITLE
weather ext

### PR DESCRIPTION
**Pull request by G1nX-01**
this extension has 1 simple objective: return weather data.
please note this is a beta and more weather data will be added soon
you cant return the coordinates from the "grab coordinates" block in any possible way cuz security

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
- blocks throw an error if location is not set, would probably be better to default the location at latitude and longitude 0
- extension does not use `canGeolocate` on the `grab coordinates` block to make sure the user is ok with their location being used
- most blocks use `console.log` after they are run which could potentially be an annoyance
- other extensions can access the coordinates retrieved from `grab coordinates` via `vm.runtime.ext_weatherext`

**Comment by G1nX-01** [comment]
i have NO idea how to fix the last issue, could i please get some help here?

**Comment by RedMan13** [comment]
> > * blocks throw an error if location is not set, would probably be better to default the location at latitude and longitude 0
> > * extension does not use `canGeolocate` on the `grab coordinates` block to make sure the user is ok with their location being used
> > * most blocks use `console.log` after they are run which could potentially be an annoyance
> > * other extensions can access the coordinates retrieved from `grab coordinates` via `vm.runtime.ext_weatherext`
> 
> i have NO idea how to fix the last issue, could i please get some help here?

me when 
```js
if (!this.longitude) return
if (!this.latitude) return
```
or even
```js
  constructor() {
    this.latitude = 0;
    this.longitude = 0;
  }
```

**Comment by G1nX-01** [comment]
> > > * blocks throw an error if location is not set, would probably be better to default the location at latitude and longitude 0
> > > * extension does not use `canGeolocate` on the `grab coordinates` block to make sure the user is ok with their location being used
> > > * most blocks use `console.log` after they are run which could potentially be an annoyance
> > > * other extensions can access the coordinates retrieved from `grab coordinates` via `vm.runtime.ext_weatherext`
> > 
> > 
> > i have NO idea how to fix the last issue, could i please get some help here?
> 
> me when
> 
> ```js
> if (!this.longitude) return
> if (!this.latitude) return
> ```
> 
> or even
> 
> ```js
>   constructor() {
>     this.latitude = 0;
>     this.longitude = 0;
>   }
> ```

i meant the issue that made the extensions able to get the coordinates

**Comment by RedMan13** [comment]
> > > > * blocks throw an error if location is not set, would probably be better to default the location at latitude and longitude 0
> > > > * extension does not use `canGeolocate` on the `grab coordinates` block to make sure the user is ok with their location being used
> > > > * most blocks use `console.log` after they are run which could potentially be an annoyance
> > > > * other extensions can access the coordinates retrieved from `grab coordinates` via `vm.runtime.ext_weatherext`
> > > 
> > > 
> > > i have NO idea how to fix the last issue, could i please get some help here?
> > 
> > 
> > me when
> > ```js
> > if (!this.longitude) return
> > if (!this.latitude) return
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or even
> > ```js
> >   constructor() {
> >     this.latitude = 0;
> >     this.longitude = 0;
> >   }
> > ```
> 
> i meant the issue that made the extensions able to get the coordinates

i see

**Comment by RedMan13** [comment]
> > * blocks throw an error if location is not set, would probably be better to default the location at latitude and longitude 0
> > * extension does not use `canGeolocate` on the `grab coordinates` block to make sure the user is ok with their location being used
> > * most blocks use `console.log` after they are run which could potentially be an annoyance
> > * other extensions can access the coordinates retrieved from `grab coordinates` via `vm.runtime.ext_weatherext`
> 
> i have NO idea how to fix the last issue, could i please get some help here?

you could make a object inside the extension's env instead of inside the class and store the long and lat there

**Comment by JeremyGamer13** [comment]
do you plan on still working on this? im still open to adding this if the changes do get made eventually

**Comment by Ianyourgod** [comment]
the only time that java has something good: private variables

**Comment by RedMan13** [comment]
> the only time that java has something good: private variables

me when your mom:

**Comment by JeremyGamer13** [comment]
what? i didnt merge that

**Comment by derpygamer2142** [comment]
haxed?

**Pull request merged**
