### PR TITLE
Create Sty-Lists

### PR DESCRIPTION
**Pull request by SharkPool-SP**
**I posted enough leaks for you guys to know what this is :trollface:**

### CODE REVIEW

**Comment by TheShovel** [comment]
Code that searches for HTML elements should search for class prefixes, not for class prefixes with temporary IDs.
This can brake projects with editor updates quickly. Updating the extension every time the editor is updated is not a reliable option.
Screenshot_20231115_171333
Please search for `monitor_list-row_` instead of `monitor_list-row_okCNn` and so on.

**Comment by SharkPool-SP** [comment]
> Code that searches for HTML elements should search for class prefixes, not for class prefixes with temporary IDs.
> 
> This can brake projects with editor updates quickly. Updating the extension every time the editor is updated is not a reliable option.
> 
> Screenshot_20231115_171333
> 
> Please search for `monitor_list-row_` instead of `monitor_list-row_okCNn` and so on.

Oh shit I think I forgot some of them

**Comment by SharkPool-SP** [comment]
> Code that searches for HTML elements should search for class prefixes, not for class prefixes with temporary IDs.
> 
> This can brake projects with editor updates quickly. Updating the extension every time the editor is updated is not a reliable option.
> 
> Screenshot_20231115_171333
> 
> Please search for `monitor_list-row_` instead of `monitor_list-row_okCNn` and so on.

That's what it does? The code you showed is just for the column rendering, it doesn't do any searching, just adds html.

**Comment by TheShovel** [comment]
> > Code that searches for HTML elements should search for class prefixes, not for class prefixes with temporary IDs.
> > This can brake projects with editor updates quickly. Updating the extension every time the editor is updated is not a reliable option.
> > Screenshot_20231115_171333
> > Please search for `monitor_list-row_` instead of `monitor_list-row_okCNn` and so on.
> 
> That's what it does? The code you showed is just for the column rendering, it doesn't do any searching, just adds html.

My point still stands. It shouldn't use IDs like that.

**Comment by SharkPool-SP** [comment]
> > > Code that searches for HTML elements should search for class prefixes, not for class prefixes with temporary IDs.
> 
> > > This can brake projects with editor updates quickly. Updating the extension every time the editor is updated is not a reliable option.
> 
> > > Screenshot_20231115_171333
> 
> > > Please search for `monitor_list-row_` instead of `monitor_list-row_okCNn` and so on.
> 
> > 
> 
> > That's what it does? The code you showed is just for the column rendering, it doesn't do any searching, just adds html.
> 
> 
> 
> My point still stands. It shouldn't use IDs like that.

I don't get it though, it doesn't change anything? What should I do, use my own id?

**Comment by SharkPool-SP** [comment]
> > > Code that searches for HTML elements should search for class prefixes, not for class prefixes with temporary IDs.
> > > This can brake projects with editor updates quickly. Updating the extension every time the editor is updated is not a reliable option.
> > > Screenshot_20231115_171333
> > > Please search for `monitor_list-row_` instead of `monitor_list-row_okCNn` and so on.
> > 
> > 
> > That's what it does? The code you showed is just for the column rendering, it doesn't do any searching, just adds html.
> 
> My point still stands. It shouldn't use IDs like that.

Fixed. It now copies and pastes the class ID.

Also now supports packaged projects 👍

**Pull request merged**
