### PR TITLE
Goose Extension

### PR DESCRIPTION
**Pull request by Pfoxj**
Banner:
Thumb

Description:
A Simple Extension With Goose Sounds (May Not Work On Some Computers)

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
This is just a joke extension that doesn't event work. 💀

**Comment by Pfoxj** [comment]
> This is just a joke extension that doesn't even work. 💀

It Should, It Works On My End And I Just Need a Patch, That's Why "May Not Work On Some Computers" Is In The Description

**Comment by SharkPool-SP** [comment]
If that's the case, it's best not to add the extensions. Either way, it didn't load. It didn't show up or do anything.

**Comment by Pfoxj** [comment]
> If that's the case, it's best not to add the extensions. Either way, it didn't load. It didn't show up or do anything.

I Don't Know Why It's Not Working, I Made It With TurboBuilder But It Only Worked On My Old Chromebook For Some Reason.

**Comment by SharkPool-SP** [comment]
> > If that's the case, it's best not to add the extensions. Either way, it didn't load. It didn't show up or do anything.
> 
> 
> 
> I Don't Know Why It's Not Working, I Made It With TurboBuilder But It Only Worked On My Old Chromebook For Some Reason.

Keep in mind TurboBuilder is a WIP, and iirc extensions made by it aren't allowed on **this** gallery because of formatting and such.

**Comment by Pfoxj** [comment]
> > > If that's the case, it's best not to add the extensions. Either way, it didn't load. It didn't show up or do anything.
> > 
> > 
> > I Don't Know Why It's Not Working, I Made It With TurboBuilder But It Only Worked On My Old Chromebook For Some Reason.
> 
> Keep in mind TurboBuilder is a WIP, and iirc extensions made by it aren't allowed on **this** gallery because of formatting and such.

Oh, Right, Kinda Forgot That...

**Comment by Pfoxj** [comment]
> > > > If that's the case, it's best not to add the extensions. Either way, it didn't load. It didn't show up or do anything.
> > > 
> > > 
> > > I Don't Know Why It's Not Working, I Made It With TurboBuilder But It Only Worked On My Old Chromebook For Some Reason.
> > 
> > 
> > Keep in mind TurboBuilder is a WIP, and iirc extensions made by it aren't allowed on **this** gallery because of formatting and such.
> 
> Oh, Right, Kinda Forgot That...

Anyway, I Moved The Goose Extention Here: [github.com/chatty/chats/pull/1](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Comment by Pfoxj** [comment]
> > Anyway, I Moved The Goose Extention Here: [github.com/chatty/chats/pull/1](https://www.youtube.com/watch?v=dQw4w9WgXcQ)
> 
> haha so funny.....

Yep, It Is, It Is

**Comment by lego7set** [comment]
> Yet, It Is, It Is

do you not understand what sarcasm is?

**Comment by Pfoxj** [comment]
> > Yet, It Is, It Is
> 
> do you not understand what sarcasm is? (edit: i actually cant tell if the comment on the sarcasm is sarcasm or not)

I Do, I Was Being Sarcastic

**Pull request closed without merging**
