### PR TITLE
Object extension

### PR DESCRIPTION
**Pull request by Skyhigh173**
add object extension, which can process large json files at a fastest rate, from 15x (write) up to 30000x (read) compared to json ext *lol*

### CODE REVIEW

**Comment by Skyhigh173** [comment]
There's bug in PM while this is normal in Turbowarp

**Comment by JeremyGamer13** [comment]
> There's bug in PM while this is normal in Turbowarp

what is the bug

**Comment by Skyhigh173** [comment]
> > There's bug in PM while this is normal in Turbowarp
> 
> 
> 
> what is the bug

Try to load this extension into PM

**Comment by Skyhigh173** [comment]
Perhaps the "bug" is the sandboxed issue

**Comment by JeremyGamer13** [comment]
nope, PM automatically casts inputs to their ArgumentType which seems to break this extension
image

**Comment by Skyhigh173** [comment]
lol

**Comment by Skyhigh173** [comment]
@JeremyGamer13 my suggestion is to add `Scratch.ArgumentType.Any` so it won't cast value

**Comment by JeremyGamer13** [comment]
add that to the argument objects, the ones with `type` or `defaultValue`

**Pull request merged**
