### PR TITLE
Create perceptron.js

### PR DESCRIPTION
**Pull request by engineering-wrench**
**this is an extension to add a neural network utility** (without internet)

### CODE REVIEW

**Review by CodeFoxy-Github — COMMENTED** [review]
You Need Add your extension to src/lib/extensions.js or it won't show on the website
like this 
````
/*
    note to contributors & developers that can read JSON:
        the extra commas are added at the end of each thing
        to help copy & pasting work better
        pleas dont remove them :)
*/
export default [
     {
        name: "Update File (Direct Access)",
        description: "A simple extension that uses the File System Access API to update files dynamically.",
        code: "Anonymous_cat1/updateFile.js",
        banner: "Anonymous_cat1/updateFile.svg",
        creator: "Anonymous-cat1",
        isGitHub: true,
    },
    {
        name: "CloudLink",
        description: "A powerful WebSocket extension for Scratch. Allows for online connectivity to servers for things like multiplayer.",
        code: "MikeDev101/cloudlink.js",
        banner: "MikeDev101/cloudlink.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "E2EE",
        description: "A general-purpose E2EE (End-to-End Encryption) extension for Scratch.",
        code: "MikeDev101/e2ee.js",
        banner: "MikeDev101/e2ee.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "WebRTC",
        description: "A barebones WebRTC implementation.",
        code: "MikeDev101/webrtc.js",
        banner: "MikeDev101/webrtc.svg",
        creator: "MikeDev101",
        isGitHub: true,
    },
    {
        name: "Pen+",
        description: "Extended pen section! Adds blocks for drawing triangles using textures and tints, drawing images and editing their pixels, etc.",
        code: "ObviousAlexC/PenPlus.js",
        banner: "ObviousAlexC/PenPlus.svg",
        creator: "pinksheep2917",
    },
    {
        name: "Boxed Physics",
        description: "Implements the Box2D physics engine into PenguinMod, adding joints, springs, etc. This is different from TurboWarp's implementation.",
        code: "pooiod/Box2D.js",
        banner: "pooiod/B2Dimg.svg",
        creator: "pooiod7",
    },
    {
        name: "Object",
        description: "Handle large JSON files at an extreme speed.",
        code: "skyhigh173/object.js",
        banner: "skyhigh173/object.svg",
        creator: "skyhigh173",
        isGitHub: true,
    },
    {
        name: "3D Math",
        description: "A handful of utilities for making your own sprite-based 3D engine.",
        code: "ObviousAlexC/3DMath.js",
        banner: "ObviousAlexC/3DMath.svg",
        creator: "pinksheep2917",
    },
    {
        name: "Sprite Effects",
        description: "Apply new non-vanilla effects to sprites and the screen as a whole!",
        code: "SharkPool/Sprite-Effects.js",
        banner: "SharkPool/Sprite-Effects.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "PenguinAI",
        description: "Talk to AI! Use Models like DALL-E-3, GPT, LLama, Claude, and more!",
        code: "MubiLop/penguingpt.js",
        banner: "MubiLop/penguingpt.png",
        creator: "MubiLop",
        isGitHub: false,
    },
    {
        name: "Scope Variable",
        description: "Manage your variables in a block-like structure.",
        code: "0znzw/ScopeVars.js",
        banner: "0znzw/ScopeVars.png",
        creator: "Ashimee",
        isGitHub: true,
    },
    {
        name: "Variables Expanded",
        description: "New variable blocks and new display monitor types.\n(some contributions by DogeIsCut)",
        code: "SharkPool/Variables-Expanded.js",
        banner: "SharkPool/Variables-Expanded.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sty-Lists",
        description: "Customize and organize list monitors.",
        code: "SharkPool/Sty-Lists.js",
        banner: "SharkPool/Sty-Lists.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Display Text",
        description: "An extremely customizable text engine for your projects. Assign text elements to IDs and customize every little setting about them.",
        code: "SharkPool/Display-Text.js",
        banner: "SharkPool/Display-Text.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sprite Parenting",
        description: "Link sprites together and make them follow the parent.",
        code: "SharkPool/Sprite-Linking.js",
        banner: "SharkPool/Sprite-Linking.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Pause Utilities",
        description: "Utilities for pausing & unpausing scripts, sprites, and projects. Also allows for running blocks when the project is paused.",
        code: "SharkPool/Pause-Utilities.js",
        banner: "SharkPool/Pause-Utilities.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Better Input",
        description: "Expansion to the Ask and Wait blocks. Adds custom modals with effects, transitions, buttons, dropdowns, etc.",
        code: "SharkPool/BetterInput.js",
        banner: "SharkPool/BetterInput.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Random Utilities",
        description: "Many blocks related to generating random values, including seed-based number generation, true number generation, UUID's, random strings, etc.",
        code: "Gen1x/random_utils.js",
        banner: "Gen1x/randomutils.png",
        creator: "G1nX",
    },
    {
        name: "Cockatiel Location",
        description: "Fetch Users' IP Addresses and Location.",
        code: "bruhbeast-pixel/CockatielLocation.js",
        banner: "bruhbeast-pixel/CockatielLocation.svg",
        creator: "bruhbeast-pixel",
        isGitHub: true,
    },
    {
        name: "Particle Tools",
        description: "Tools for making particle engines easier.",
        documentation: "particle-tools",
        code: "SharkPool/Particle-Tools.js",
        banner: "SharkPool/Particle-Tools.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "More Types",
        description: "Adds more value types to PenguinMod, implementing Functions, Objects, Arrays, Sets, Maps, Symbols and Nothing.",
        code: "VeryGoodScratcher42/More-Types.js",
        banner: "VeryGoodScratcher42/More-Types.png",
        creator: "VeryGoodScratcher42",
        isGitHub: false,
    },
    {
        name: "PenguinHook",
        description: "Send Webhook requests, that can be Discord or any type of webhook.",
        code: "MubiLop/penguinhook.js",
        banner: "MubiLop/penguinhook.png",
        creator: "MubiLop",
        isGitHub: false,
    },
    {
        name: "Toast Notifications",
        description: "Did you want alerts? Notificationss that are easily customizable? This is the only and best notification extension!",
        code: "MubiLop/toastnotifs.js",
        banner: "MubiLop/toastnotifs.png",
        creator: "MubiLop and themeatly2",
        isGitHub: false,
    },
    {
        name: "Tile Grids",
        description: "Place sprites on grids.",
        code: "SharkPool/Tile-Grids.js",
        banner: "SharkPool/Tile-Grids.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Animations",
        description: "Play animations and keyframes for your sprites.",
        code: "SharkPool/Animations.js",
        banner: "SharkPool/Animations.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Time Calculations",
        description: "Blocks for calculating and converting time.",
        code: "SharkPool/Time-Calculations.js",
        banner: "SharkPool/Time-Calculations.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    // this extension is completely dead as of now
    // {
    //     name: "Better Storage",
    //     description: "Like PenguinMod's Storage Extension, but with a couple more features, and faster servers.",
    //     code: "Gen1x/better_storage.js",
    //     banner: "Gen1x/betterstorage.png",
    //     creator: "G1nX",
    // },
    // this extension is completely dead as of now
    // {
    //     name: "Mouth Washer",
    //     description: "Includes many utilities related to cleaning bad words, swearing and profanity. Thought of as an extra layer of security for filtering messages.\n\n(ft. violet and jwklong)",
    //     code: "Gen1x/mouth_washer.js",
    //     banner: "Gen1x/mw-placeholder.png",
    //     creator: "G1nX",
    // },
    {
        name: "Mathematics",
        description: "Complicated maths extension for nerds.",
        code: "jwklong/mathematics.js",
        banner: "jwklong/mathematics.png",
        creator: "jwklong",
        isGitHub: true,
    },
    {
        name: "Font Manager",
        description: "Manage, create, and delete fonts.\n(Some contributions by Ashimee)",
        code: "SharkPool/Font-Manager.js",
        banner: "SharkPool/Font-Manager.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Sound Waves",
        description: "Make sounds with oscillators!",
        code: "SharkPool/Sound-Waves.js",
        banner: "SharkPool/Sound-Waves.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Recording",
        description: "Record your voice while you run your projects!",
        code: "SharkPool/Recording.js",
        banner: "SharkPool/Recording.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Big Decimal",
        description: "High precision operations. (Support decimals)",
        code: "qxsck/big-decimal.js",
        banner: "qxsck/big-decimal.svg",
        creator: "qxsck",
        isGitHub: true,
    },
    {
        name: "Git Penguin",
        description: "Make requests and control the files for your GitHub repository.",
        code: "justablock/gitpenguin.js",
        banner: "justablock/gitpenguin.png",
        creator: "justablock",
        isGitHub: false, 
    },
    {
        name: "Pang API",
        description: "Fetch information from the PenguinMod API.",
        code: "SammerLOL/pangapi.js",
        banner: "SammerLOL/pangapi.png",
        creator: "oc9x97",
        isGitHub: true,
    },
    {
        name: "Discord Auth",
        description: "Login with discord to your projects. Identify users by ID and username in a secure and easy way!",
        code: "NotHouse/DiscordAuth.js",
        banner: "NotHouse/DiscordAuth-banner.png",
        creator: "enderhacker",
        isGitHub: true,
    },
    {
        name: "Online Captcha",
        description: "Protect your project with simple, easy to use captcha implementation. Fully client-side, bypass-proof captcha solution!",
        code: "NotHouse/OnlineCaptcha.js",
        banner: "NotHouse/OnlineCaptcha-banner.png",
        creator: "enderhacker",
        isGitHub: true,
    },
    {
        name: "Twitch",
        description: "Communicate with your Twitch Chat on PenguinMod!\n\nPenguinMod is not affiliated with Twitch.",
        code: "bop_tw/Twitch.js",
        banner: "bop_tw/Twitch.png",
        creator: "bop_tw",
        isGitHub: false,
    },
    {
        name: "Scratchblocks",
        description: "Generate blocks in the Scratch3, or Scratch2 format.",
        code: "pooiod/Scratchblocks.js",
        banner: "pooiod/Scratchblocks.svg",
        creator: "pooiod7",
    },
    {
        name: "Speech Bubbles",
        description: "Allows for futher customizable speech bubbles.",
        code: "SharkPool/Speech-Bubbles.js",
        banner: "SharkPool/Speech-Bubbles.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "SoundCloud API",
        description: "Fetch Songs and Statistics from SoundCloud.",
        code: "SharkPool/SoundCloud-API.js",
        banner: "SharkPool/SoundCloud-API.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "Spotify API",
        description: "Fetch statistics and information from songs, and play samples from Spotify.",
        code: "SharkPool/Spotify.js",
        banner: "SharkPool/Spotify.svg",
        creator: "SharkPool-SP",
        isGitHub: true,
    },
    {
        name: "TurboWeather",
        description: "Show weather and location data for any place in our world. Data that could be used for doxxing is deleted from results.",
        code: "RubyDevs/turboweather.js",
        banner: "RubyDevs/turboweather.webp",
        documentation: "TurboWeather",
        creator: "RubyDevs",
    },
    {
        name: "CORS Proxy",
        description: "Accessible CORS Proxies for fetching information with PenguinMod.",
        code: "NamelessCat/corsproxy.js",
        banner: "NamelessCat/corsproxy.png",
        creator: "NamelessCat",
    },
    {
        name: "Extension Exposer",
        description: "Access the raw functions from other extensions.",
        code: "TheShovel/extexp.js",
        banner: "TheShovel/placeholder-extexp.png",
        creator: "TheShovel",
        isGitHub: true,
    },
    {
        name: "Project Page",
        description: "Modify and affect the studio project page from the code. How annoying can an extension possibly be?",
        code: "jwklong/projectpage.js",
        banner: "jwklong/projectpage.png",
        creator: "jwklong",
        isGitHub: true,
    },
    {
        name: "All Menus",
        description: "Every dropdown menu for each block, in one extension.",
        code: "Lily/AllMenus.js",
        banner: "Lily/AllMenus.svg",
        creator: "LilyMakesThings",
        isGitHub: false,
    },
    {
        name: "More Fields",
        description: "Custom Field Types",
        code: "Ashime/MoreFields.js",
        banner: "0znzw/MoreFields.png",
        creator: "Ashimee",
        isGitHub: true,
    },
    {
        name: "Beepbox Player",
        description: "Play, edit, and read songs from any BeepBox mod directly from the URL or JSON!",
        code: "DogeisCut/BeepBoxPlayer.js",
        banner: "DogeisCut/BeepBoxPlayer.svg",
        creator: "DogeisCut",
        isGitHub: true, 
    },
    {
        name: "CATS",
        description: "Blocks related to cats.",
        code: "Gen1x/CATS.js",
        banner: "Gen1x/cats.png",
        creator: "G1nX",
    },
    {
        name: "Counter++",
        description: "Count anything, at any time, in PenguinMod!",
        code: "MrRedstonia/counterplusplus.js",
        banner: "MrRedstonia/counterplusplus.png",
        creator: "MrRedstonia",
        isGitHub: true,
    },
    {
        name: "How many lines?",
        description: "Blocks to determine the amount of new lines in a piece of text.",
        code: "Monochromasity/howmanylines.js",
        banner: "Monochromasity/placeholder-howmanylines.png",
        creator: "Monochromasity",
        isGitHub: true,
    },
    {
        name: "Free Servers",
        description: "Here you can find a free server for your projects. And also check whether it is working now or not.\n\nЗдесь вы можете найти бесплатный сервер для своих проектов. А также проверить, работает он сейчас или нет.",
        code: "WAYLIVES/FreeServers.js",
        banner: "WAYLIVES/FreeServersIMG.svg",
        documentation: "FreeServers",
        creator: "WAYLIVES",
        isGitHub: false,
    },
    {
        name: "Text To Speech: Redone",
        description: "Generate better TTS! Made using TTS Tool API!",
        code: "PuzzlingGGG/ttsr.js",
        banner: "PuzzlingGGG/TTSR.png",
        creator: "puzzlingGGG",
        isGitHub: false,
    },
    {
        name: "Video Sharing",
        description: "Share your screen or camera to your projects!",
        code: "pooiod/VideoSharing.js",
        banner: "pooiod/VideoSharing.svg",
        creator: "pooiod",
        isGitHub: true,
    },
    {
        name: "File Upload",
        description: "Upload files to the Network, can also used with Files extension.",
        code: "Codefoxy/cfupload.js",
        banner: "Codefoxy/cfupload.svg",
        creator: "Codefoxy",
        isGitHub: false,
    },
    {
        name: "Perceptron",
        description: "a neural network utility that runs in local",
        code: "artem_p4/perceptron.js",
        banner: "",
        creator: "samllea1, artem_p4, ChopaChop",
        isGitHub: false,
    }
];
````
### Ps. you can just paste it

**Comment by RedMan13** [comment]
@CodeFoxy-Github please do not minimod
it is ABSOLUTELY and ENTIRELY within our acceptance to implement the extension info *for* a contributor rather then having them implement it for themselves
 if the contributor did intend to implement it for themselves all the info required to do so is layed out within the repos readme

**Comment by RedMan13** [comment]
> **this is an extension to add a neural network utility** (without internet)

which btw, do you have a banner for the extension?

**Comment by CodeFoxy-Github** [comment]
Nah i dont have but i can make one

**Comment by SharkPool-SP** [comment]
You shouldnt be using turbobuilder extension format. Please use the proper format, take examples from other extensions in this rep

**Comment by engineering-wrench** [comment]
> Вы не должны использовать формат расширения turbobuilder. Пожалуйста, используйте правильный формат, возьмите примеры из других расширений в этом реп

ok

**Comment by engineering-wrench** [comment]
> > **это расширение для добавления утилит нейронной сети** (без интернета)
> 
> Кстати, у вас есть баннер для расширения?

not yet

**Comment by RedMan13** [comment]
alr

**Comment by engineering-wrench** [comment]
> Вы не должны использовать формат расширения turbobuilder. Пожалуйста, используйте правильный формат, возьмите примеры из других расширений в этом реп

I rewrote the code as you asked (https://github.com/engineering-wrench/scratch-ai),
how do I update it?

**Comment by RedMan13** [comment]
just add another commit to the repo this pr is sourcing from

**Comment by RedMan13** [comment]
as pr's are just notes to say merge these two repos, not whole containers of.tbings to merge

**Comment by engineering-wrench** [comment]
> просто добавьте еще один коммит в репозиторий, из которого исходит этот pr

I did

**Comment by RedMan13** [comment]
the change is now I'm this pr

**Comment by engineering-wrench** [comment]
> > **this is an extension to add a neural network utility** (without internet)
> 
> which btw, do you have a banner for the extension?

oh, man
literally create now: https://github.com/engineering-wrench/scratch-ai/blob/main/icon.png

**Comment by RedMan13** [comment]
k

**Comment by RedMan13** [comment]
ok so a couple minor issues
the train block will throw a type error when ran with no training data to train with (or atleast after all training data has been cleared)
and all states that are supposed to throw errors simply return when they should use throw instead
also there are a bunch of messages returned at the end of command blocks that never actually go anywhere because there command blocks and wont show return values

**Comment by RedMan13** [comment]
oh also i forgot to mention, the show documentation points to a empty github wiki page when it should instead point to a docs page here on the extension gallery

**Comment by RedMan13** [comment]
if there are no docs the button should just be omitted for now

**Comment by engineering-wrench** [comment]
> ой, еще я забыл упомянуть, что документация шоу указывает на пустую страницу вики на github, хотя вместо этого она должна указывать на страницу документации здесь, в галерее расширений

Could she be citing another source?

**Comment by engineering-wrench** [comment]
@SharkPool-SP

Sure?

**Comment by RedMan13** [comment]
oh oops I forgot

**Pull request merged**
