### PR TITLE
Bug fix...

### PR DESCRIPTION
**Pull request by CodeFoxy-Github**
It will only process the last data fetched..so i added await or it 
image

### CODE REVIEW

**Comment by CodeFoxy-Github** [comment]
updated 
image

**Comment by CodeFoxy-Github** [comment]
@SharkPool-SP  Real QUICK

**Comment by RedMan13** [comment]
ok sure

**Comment by RedMan13** [comment]
why is there a delay if it uses thw promise system?

**Comment by RedMan13** [comment]
the promise api in js is explicitly to solve the case of having an api that cant or wont resolve by the time of completion (i.e. literally all webrequests in all languages everywhere)

**Comment by RedMan13** [comment]
also without awaiting ghe delay function it literally wont do anything at all

**Comment by CodeFoxy-Github** [comment]
no it works IDK why

**Comment by CodeFoxy-Github** [comment]
await deleted it does nothing i just testing

**Comment by CodeFoxy-Github** [comment]
@RedMan13 bro merge?

**Comment by CodeFoxy-Github** [comment]
oops timezone...

**Comment by CodeFoxy-Github** [comment]
@SharkPool-SP

**Pull request merged**
