### PR TITLE
Pen+ Compat Update

### PR DESCRIPTION
**Pull request by David-Orangemoon**

### CODE REVIEW

**Comment by David-Orangemoon** [comment]
The update done. I'm going to start working on collisions and extension based sorting next.

**Comment by David-Orangemoon** [comment]
Fixed some bugs.

**Comment by JeremyGamer13** [comment]
- i cant tell if this is work in progress or not since it keeps changing
- a block's opcode is changed which could corrupt projects
- im not sure how i feel about the addons being used here, might be better if i just made a proper way to do this

**Comment by David-Orangemoon** [comment]
> * i cant tell if this is work in progress or not since it keeps changing
> 
>     * a block's opcode is changed which could corrupt projects
> 
>     * im not sure how i feel about the addons being used here, might be better if i just made a proper way to do this

what block. also I'll remove the addons thing.
I was also just making slight adjustments. But other than that its done!

**Comment by David-Orangemoon** [comment]
Shoot I did something

**Comment by David-Orangemoon** [comment]
@JeremyGamer13 It's finished now.

**Comment by David-Orangemoon** [comment]
Also the op code changes where due to two blocks having overlapping op codes.

**Pull request merged**
