### PR TITLE
Add Socket.IO extension.

### PR DESCRIPTION
**Pull request by TechGigant**
image

### CODE REVIEW

**Comment by RedMan13** [comment]
you cant import external modules inside the extension
if an external module is necessary it must be built into the extension file and can not ever be imported from an external library

**Comment by TechGigant** [comment]
I have tried that before but exactly that didn't work.

**Comment by RedMan13** [comment]
well you still can not import it externally so

**Comment by TechGigant** [comment]
Why?

**Comment by RedMan13** [comment]
it is also a much better practice as it ensures that nomatter what happens to the service you will always have the code for the extension to work

**Comment by TechGigant** [comment]
Ok well this extension isn't possible then.

**Pull request closed without merging**
