### PR TITLE
Add WebRTC & E2EE Extensions

### PR DESCRIPTION
**Pull request by MikeDev101**
This adds the [cloudlink-omega/scratch3-webrtc](https://github.com/cloudlink-omega/scratch3-webrtc) and [cloudlink-omega/e2ee](https://github.com/cloudlink-omega/e2ee) extensions to PenguinMod.

### CODE REVIEW

**Comment by MikeDev101** [comment]
Same issue as when I made a PR for cloudlink 4 - Needs to run unsandboxed

**Comment by MikeDev101** [comment]
wait, I did a stupid and forgot that it's sandboxed in previews

**Comment by JeremyGamer13** [comment]
> Your extension should be MIT licensed (not compatible with the MIT license, should be the actual MIT license. This may change in the future.)
Is the WebRTC extension under the MIT license? (asking since the E2EE extension states MIT but WebRTC has something else)

**Comment by MikeDev101** [comment]
> > Your extension should be MIT licensed (not compatible with the MIT license, should be the actual MIT license. This may change in the future.)
> 
> Is the WebRTC extension under the MIT license? (asking since the E2EE extension states MIT but WebRTC has something else)

It is, just not immediately present in the source file (Forgot about that last minute, it's in the original repos in `LICENSE`)

**Comment by MikeDev101** [comment]
I have updated the extensions to clarify licenses.

**Pull request merged**
