### PR TITLE
PenguinScript extension

### PR DESCRIPTION
**Pull request by lego7set**
For those thinking that this is an april fools pull request, it is not.

This creates an extension that uses a transpiler to transpile "PenguinScript" into JavaScript.

Unfortunately, due to the project's size, I needed to bundle it with webpack. I assure you that this extension is not malicious. You can check it against this [github action](https://github.com/lego7set/PenguinScript/actions/runs/8547509878)

I apologize for the poor quality of the extension banner :trollface: 

Please let me know if there are any bugs

### CODE REVIEW

**Comment by AshimeeAlt** [comment]
off-topic but you left your auth key in the rc https://github.com/lego7set/PenguinScript/blob/main/.npmrc

**Comment by RedMan13** [comment]
the whaet

**Comment by AshimeeAlt** [comment]
> it would have been safer to email him about this 💀

i forgot you guys log all this github sh*t 💀

**Comment by AshimeeAlt** [comment]
i also dont have his email

**Comment by RedMan13** [comment]
> i also dont have his email

is it not on one of the account pages? 💀

**Comment by RedMan13** [comment]
also what is fhis auth key for
i truely do jot understand what issuebis being referred to here

**Comment by PuzzlingGGG** [comment]
penguin that script

**Comment by AshimeeAlt** [comment]
> chill out guys the auth key was disabled before i made the repo public.

phew, also we were chill lol

**Pull request closed without merging**
