### PR TITLE
Add scrandled to Extensions Menu in editor? please?

### PR DESCRIPTION
**Pull request by Monochromasity**
I'm making an extensions site (https://scrandled.vercel.app) and i was wondering if you could add it to the extensions menu in the editor? (sorry for making an empty file but there wasnt another way to contact anyone that i could find that isn't discord cause im not allowed discord)

### CODE REVIEW

**Comment by WAYLIVES** [comment]
Hi! Of course you can, we will be only too happy ;) And if you want to ask us a question, then ask in "issues":

изображение

**Comment by WAYLIVES** [comment]
I think you already know how to add extensions, and if you don't, then read this article: https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/blob/main/README.md
If you still don't understand how to add extensions, then ask a question, we will definitely help you :trollface:

**Comment by Monochromasity** [comment]
> I think you already know how to add extensions, and if you don't, then read this article: https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/blob/main/README.md If you still don't understand how to add extensions, then ask a question, we will definitely help you :trollface:

It's easier to add extensions to my own site than wait ages for it to be added to the gallery, that's why I asked, also I'm not sure how to make an issue, I'm still figuring out how to use GitHub

**Comment by Monochromasity** [comment]
Also can someone let me know when it's added if it isn't already?

**Comment by Monochromasity** [comment]
> Hi! Of course you can, we will be only too happy ;) And if you want to ask us a question, then ask in "issues":
> 
> изображение

Do you have any extensions I could add to scrandled?

**Comment by Monochromasity** [comment]
I'm going to redirect this to an issue, so this is now closed.

**Pull request closed without merging**
