### PR TITLE
Pure Emoji

### PR DESCRIPTION
**Pull request by mariocraft987**
> if you want joke blocks, make an extensions separate for them.
> &#45; ianyourgod 2024

So I did
NOT APEARING IN THE EXTENSIONS LIBRARY

### CODE REVIEW

**Comment by TheShovel** [comment]
Sorry but this is not funny. Has no skibbidy rizz

**Comment by RedMan13** [comment]
> why the fuck are you editing someone else’s extension in this pr?????????

makes sense to me

**Comment by RedMan13** [comment]
if it needs edited, it needs edited

**Comment by RedMan13** [comment]
so i just relearnwd that i can edit other peoples replies

**Comment by RedMan13** [comment]
> dear sir or madam, i whish to query you as to why you have edited this other persons files using this "pull request". i whish to know this because to me it seems quite strange that anyone would need to edit anyone elses files on this particular repository. as, for how i understand it, every single persons folder is meant to be unique to them and making changes like this just confounds me because of that concept.

sourced from "why the fuck are you editing someone else’s extension in this pr?????????"

**Comment by RedMan13** [comment]
> > if you want joke blocks, make an extensions separate for them.
> > - ianyourgod 2024
> 
> So I did NOT APEARING IN THE EXTENSIONS LIBRARY

you never added the extension back to rhe list 💀

**Comment by mariocraft987** [comment]
if only merge pull requests could be deleted

**Pull request closed without merging**
