### PR TITLE
Add Spotify Extension

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Screenshot 2023-11-13 221701

### CODE REVIEW

**Comment by WAYLIVES** [comment]
Hello, very cool, but for some reason nothing works and the last three blocks display an error :(
изображение

**Comment by SharkPool-SP** [comment]
> Hello, very cool, but for some reason nothing works and the last three blocks display an error :(
> 
> изображение
> 
> 

It seems to be a internet problem on your side. Your internet is probably blocking Spotify or something

**Comment by TheShovel** [comment]
Same thing happens to me.
Screenshot_20231115_170916

**Comment by SharkPool-SP** [comment]
> Same thing happens to me.
> 
> Screenshot_20231115_170916
> 
> 

Strange, it works for me? What's ur internet connection?

**Comment by WAYLIVES** [comment]
### Map of countries where Spotify works (Карта стран, где работает Spotify).

изображение

**Comment by TheShovel** [comment]
Spotify works in my country. The issue might be that you have to log into Spotify in your browser first, then use the extension.

**Comment by SharkPool-SP** [comment]
> Spotify works in my country. The issue might be that you have to log into Spotify in your browser first, then use the extension.

Idk, cuz it works on my Mac, which isn't signed in.

**Comment by SharkPool-SP** [comment]
> Spotify works in my country. The issue might be that you have to log into Spotify in your browser first, then use the extension.

Figured out the problem, PenguinMod doesnt like Scratch.fetch().

I changed the code, so now it should work for you :) 
~cheers!

**Comment by WAYLIVES** [comment]
> > Spotify works in my country. The issue might be that you have to log into Spotify in your browser first, then use the extension.
> 
> Figured out the problem, PenguinMod doesnt like Scratch.fetch().
> 
> I changed the code, so now it should work for you :) ~cheers!

### Oh yes it worked!

**Comment by JeremyGamer13** [comment]
sorry for taking a while but i will come back in a few minutes to fix a problem:
playing songs via the extension does not respect/support the Pause button, Recording addon, nor the volume slider addon

**Comment by JeremyGamer13** [comment]
yea "a few minutes" :trollface:

**Pull request merged**
