### PR TITLE
Change PenguinGPT to PenguinAI

### PR DESCRIPTION
**Pull request by cicerorph**
(Don't pull yet, also i am doing an pull request on the editor aswell so the ext doesnt break there)

### CODE REVIEW

**Comment by cicerorph** [comment]
Ok can pull now

**Comment by JeremyGamer13** [comment]
do not rename extension files, it will break compat

**Review by JeremyGamer13 — CHANGES_REQUESTED** [review]
files are renamed & the extension id is renamed, neither of those should be changed

**Comment by cicerorph** [comment]
Fixed

**Review by JeremyGamer13 — APPROVED** [review]
menu value change is apparently because old one didnt work before so this is good

**Pull request merged**
