### PR TITLE
add Text To Speech: Redone

### PR DESCRIPTION
**Pull request by PuzzlingGGG**
it a better tts extension

### CODE REVIEW

**Comment by PuzzlingGGG** [comment]
🗣️ 🔥

**Comment by PuzzlingGGG** [comment]
Guys please

**Comment by RedMan13** [comment]
uhhhhhhh bleh

**Comment by PuzzlingGGG** [comment]
is that yes or no or do i gotta get gsa on this one:troll:

**Comment by RedMan13** [comment]
> is that yes or no or do i gotta get gsa on this one:troll:

i am gsa :trollface:

**Comment by PuzzlingGGG** [comment]
oh im blind :bleh:

**Comment by RedMan13** [comment]
skill issue

**Pull request merged**
