### PR TITLE
Discord Auth

### PR DESCRIPTION
**Pull request by nmsderp**
Authenticate with Discord and get their username and more (I made this cuz no one else did lol)

### CODE REVIEW

**Comment by Mariocraft987** [comment]
true..

**Comment by JeremyGamer13** [comment]
really the only issue is that it says "snailauth" on the auth screen which obviously makes sense but it would be nice if it was brand-less

**Comment by nmsderp** [comment]
i am using the same server that i use for snail ide, but i will change the auth title thingy real quick

**Comment by nmsderp** [comment]
done

**Comment by JustablockCode** [comment]
cool

**Comment by nmsderp** [comment]
@JeremyGamer13 I made the requested changes

**Comment by JeremyGamer13** [comment]
did github completely skip over this? its not in any github log & you didnt seem to see it
image

**Comment by nmsderp** [comment]
I'm gonna make this a draft for right now, I will update the server and the extension, once I'm done I'll ping Jeremy

**Comment by CharcoalAfterlife** [comment]
hm

**Comment by nmsderp** [comment]
closing cuz NotHouse made a better version

**Comment by CharcoalAfterlife** [comment]
yayayyaayayayay

**Pull request closed without merging**
