### PR TITLE
Create stringmutilation.js

### PR DESCRIPTION
**Pull request by ddededodediamante**
Extension that adds blocks that allows for text modification

### CODE REVIEW

**Comment by ddededodediamante** [comment]
pull request #100?!??!?!?!?!??!?!?!?!!

**Comment by SharkPool-SP** [comment]
Pretty much all these blocks exist already

**Comment by ddededodediamante** [comment]
Which ones?

**Comment by SharkPool-SP** [comment]
> Which ones?
Operators tab and text+

**Comment by ddededodediamante** [comment]
I can't find text+ do you mean in turbowarp gallery?

**Comment by SharkPool-SP** [comment]
> I can't find text+ do you mean in turbowarp gallery?

ye

**Comment by jwklong** [comment]
theres no extensions.js additition so cant add

**Comment by ddededodediamante** [comment]
huh

**Comment by ddededodediamante** [comment]
> theres no extensions.js additition so cant add

what is that

**Comment by ddededodediamante** [comment]
nvm i found out but how do i modify that

**Comment by ddededodediamante** [comment]
also i thought it was optional.............

**Pull request closed without merging**
