### PR TITLE
FreeServers.js

### PR DESCRIPTION
**Pull request by WAYLIVES**
# **`FREE SERVERS`**

### English:

> New extension "FreeServers". Thanks to this extension, you can view possible free servers for your online projects. And you can also determine whether the server is running or not.

### Russian:

> Новое расширение "FreeServers". Благодаря этому расширению вы можете просматривать возможные бесплатные серверы для ваших онлайн-проектов. И вы также можете определить, запущен сервер или нет.

<br>

изображение

### CODE REVIEW

**Comment by WAYLIVES** [comment]
# Example:

изображение

**Comment by WAYLIVES** [comment]
### What do I need to do?

изображение

**Comment by WAYLIVES** [comment]
What do I need to do next?

**Comment by WAYLIVES** [comment]
#### I'm ready, but I'm confused with the documentation :(

**Comment by RedMan13** [comment]
i didnt know there was a server on 127.0.0.1 :trollface:

**Comment by WAYLIVES** [comment]
True, this server does not work in Penguin Mod :(

**Comment by WAYLIVES** [comment]
# Everything is ready, I figured out the documentation))) <br> 💯

**Comment by RedMan13** [comment]
> True, this server does not work in Penguin Mod :(

it does tho, 127 is your current device and so will only work if you are hosting a server on your device

**Comment by WAYLIVES** [comment]
aha, got it

**Comment by WAYLIVES** [comment]
### Is it possible to add this extension to the gallery?

**Comment by RedMan13** [comment]
why hasn't this been merged yet?

**Comment by WAYLIVES** [comment]
> why hasn't this been merged yet?

What's included?

**Comment by AlexSchoolOH** [comment]
I'm going to check out the extension and if it works I'll merge it.

**Comment by WAYLIVES** [comment]
> I'm going to check out the extension and if it works I'll merge it.

I really hope that my code is correct :)

**Comment by David-Orangemoon** [comment]
Seems good I'll merge it and move it slightly lower in the gallery

**Pull request merged**
