### PR TITLE
(Fixed Crashing) Add Variables Expanded, the beast.....

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Monitors+:
Screenshot 2023-11-03 at 12 08 42 AM
Screenshot 2023-10-10 at 12 51 03 AM

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
for people not in the discord this hasnt been merged yet because of the crashing (yes you can easily fix it but generally extensions shouldnt be 2 clicks away from being able to crash sections of the GUI unintentionally)

**Comment by SharkPool-SP** [comment]
> for people not in the discord this hasnt been merged yet because of the crashing (yes you can easily fix it but generally extensions shouldnt be 2 clicks away from being able to crash sections of the GUI unintentionally)

I need help broski :trollface:

**Comment by JeremyGamer13** [comment]
- setting the variables value before changing to a non-scratch monitor type will reset the variable to a different value when changing to Checkbox or Text types
- you should still keep the double-click warning button in the toolbox because it still causes weird behavior in the editor regardless
- read code suggestions for more

**Comment by AlexSchoolOH** [comment]
I'll finish checking this out later, and confirm it is ready to merge.

**Comment by JeremyGamer13** [comment]
- textbox still resets to `...` when changing monitor type (but the variable value itself no longer does)
- fonts, position, and effects seem to reset if monitor types change too quickly
- display name reverts instantly as soon as the monitor type is changed

**Comment by SharkPool-SP** [comment]
> * textbox still resets to `...` when changing monitor type (but the variable value itself no longer does)
> * fonts, position, and effects seem to reset if monitor types change too quickly
> * display name reverts instantly as soon as the monitor type is changed

fixed

**Comment by JeremyGamer13** [comment]
considering the remaining problems barely cause any inconvenience, i think this is fine to merge in its current state

**Pull request merged**
