### PR TITLE
Propose pen+ v6 to be on the gallery.

### PR DESCRIPTION
**Pull request by David-Orangemoon**
What will be accepted first I'm kinda curious.
penPlus (1)

### CODE REVIEW

**Comment by Ianyourgod** [comment]
Competition between pm and tw?

**Comment by Ianyourgod** [comment]
i will look through this rn

**Comment by Ianyourgod** [comment]
nvm this is too many lines and im too lazy

**Comment by JeremyGamer13** [comment]
i can look through it after  i look through the other extension that was put first

**Comment by JeremyGamer13** [comment]
seems like theres kind of a bug with documentation buttons in pm so a dev would probably need to fix that before this gets merged

**Comment by JeremyGamer13** [comment]
a couple things
- the `turn advanced setting` block has a menu where both options have the same value (easier to see when you open the menu)
- the documentation URL doesnt seem to exist?
- extension ID should have your name in it (new requirement)
unfortunately i cant tell exactly how to use the extension due to the broken link so i dont know if theres any other errors, but otherwise looks fine

**Comment by David-Orangemoon** [comment]
> a couple things
> 
> * the `turn advanced setting` block has a menu where both options have the same value (easier to see when you open the menu)
> * the documentation URL used doesnt seem to exist?
> * extension ID should have your name in it (new requirement)
>   unfortunately i cant tell exactly how to use the extension due to the broken link so i dont know if theres any other errors, but otherwise looks fine

Its just a direct port of the turbowarp one and I've used it in penguinmod before using the add custom extension thing so I know it works.

**Comment by RedMan13** [comment]
why isnt the ext in the extension list?

**Comment by JeremyGamer13** [comment]
> why isnt the ext in the extension list?

?

**Comment by RedMan13** [comment]
> > why isnt the ext in the extension list?
> 
> ?

the extension is missing in the vercel preview

**Comment by David-Orangemoon** [comment]
I should probably learn more about the PM extension gallery before trying something like this again.

**Comment by JeremyGamer13** [comment]
understandable

**Comment by JeremyGamer13** [comment]
> > > why isnt the ext in the extension list?
> > 
> > 
> > ?
> 
> the extension is missing in the vercel preview

as long as the path to it exists its fine, if its not added to the front page in the PR then i just add it there myself

**Comment by RedMan13** [comment]
> > > > why isnt the ext in the extension list?
> > > 
> > > 
> > > ?
> > 
> > 
> > the extension is missing in the vercel preview
> 
> as long as the path to it exists its fine, if its not added to the front page in the PR then i just add it there myself

alr

**Comment by KyleKart** [comment]
last extension was missing its preview too i believe

**Comment by KyleKart** [comment]
oops didnt reply

> last extension was missing its preview too i believe

**Pull request closed without merging**
