### PR TITLE
Dev Tools

### PR DESCRIPTION
**Pull request by Ashimee**
Some dev tools for people.

### CODE REVIEW

**Comment by JeremyGamer13** [comment]
the eval block & inject html block are really the only thing stopping this from being added, this would likely not be a listed extension though and would just be added so that it's a trusted file because it's for debugging

**Comment by SurvExe1Pc** [comment]
can it just be hosted, or could I add a url parameter to show the eval and inject if the user wants it
________________________________

**Comment by JeremyGamer13** [comment]
i just dont like the idea of the eval & html injection there at all, full control of the webpage without even telling the user that anything is gonna happen

**Comment by SurvExe1Pc** [comment]
thats why its a button you have to go into the editor to do it, but i can remove it if you would like
________________________________

**Comment by JeremyGamer13** [comment]
alright i see what you mean now, for whatever reason though none of the things here seem to work anymore?
i click the buttons but nothing happens & the console says `TypeError: this.label.replaceAll is not a function`

**Comment by RedMan13** [comment]
> i just dont like the idea of the eval & html injection there at all, full control of the webpage without even telling the user that anything is gonna happen

yeah but litterally everyone in the server will just give you an extension for unrestricted eval :trollface:

**Comment by JeremyGamer13** [comment]
ok but it still needs a warning pop up :trollface:

**Comment by SurvExe1Pc** [comment]
> alright i see what you mean now, for whatever reason though none of the things here seem to work anymore? i click the buttons but nothing happens & the console says `TypeError: this.label.replaceAll is not a function`

weird I will look into it

**Comment by NexusKitten** [comment]
I've been looking at this for a while, it looks like most of the issues lie in:
1. replaceall is a stinky poopoo function that never works
2. Data acts weird after it's defined

**Comment by NexusKitten** [comment]
also im gonna steal some of your open source code 🗿

**Comment by ohiorizzking** [comment]
:skull:

**Comment by RedMan13** [comment]
> also im gonna steal some of your open source code 🗿

open saucy code

**Comment by RedMan13** [comment]
>     1. replaceall is a stinky poopoo function that never works

nuh uh

**Pull request closed without merging**
