### PR TITLE
Create WebCreator

### PR DESCRIPTION
**Pull request by bruhbeast-pixel**
Here are the _**blocks:**_
image
Here is the SVG banner:
Web Creator
SharkPool get up fast ._.

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
wont be accepted as users can run unfiltered js and html

**Comment by SharkPool-SP** [comment]
> > wont be accepted as users can run unfiltered js and html
> 
> its being run in a popup

doesn't matter

**Comment by TheShovel** [comment]
unsandboxed javascript. I frame extension can do all of this safely

**Comment by SharkPool-SP** [comment]
> unsandboxed javascript. I frame extension can do all of this safely

Me when I said that

**Comment by TheShovel** [comment]
i know but like i had to give the reason why i closed it smartass :trollface:

**Comment by RedMan13** [comment]
*it's smart Alex not ass :trollface:

**Comment by RedMan13** [comment]
what the fuck

**Comment by CodeFoxy-Github** [comment]
??? TF
My email was spamed by github

**Pull request closed without merging**
