### PR TITLE
Smart Cubes

### PR DESCRIPTION
**Pull request by mariocraft987**
https://studio.penguinmod.com/editor.html?extension=https://penguin-mod-extensions-gallery-nine.vercel.app/extensions/mariocraft987/smartCubes.js

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
No one merge this 💀

**Comment by PuzzlingGGG** [comment]
whats wrong with it

**Comment by JeremyGamer13** [comment]
> whats wrong with it

- Your extension should be created for a specific purpose. An extension with random blocks someone might need will likely not get accepted if the blocks are not in a certain theme, like math or rendering.

**Comment by PuzzlingGGG** [comment]
> > whats wrong with it
> 
> * Your extension should be created for a specific purpose. An extension with random blocks someone might need will likely not get accepted if the blocks are not in a certain theme, like math or rendering.

oh :troll_hands:

**Pull request closed without merging**
