### PR TITLE
Create hamperslogicgatesextension.js

### PR DESCRIPTION
**Pull request by adevguylol**
its me hamper if igured out the issue (I Was marked as spam) so can you please accept my first extension 👍

### CODE REVIEW

**Comment by adevguylol** [comment]
Description: adds basic logic gates (xor, nor, nand, xnor, etc) to make your life just a little bit easier.

**Comment by adevguylol** [comment]
WAKE UP vhjkbfedhjgfdhigf

**Comment by jwklong** [comment]
no extensions.js modification, cant merge

**Comment by NexusKitten** [comment]
doesn't even remotely fit syntax, also has audio support for some reason???

**Pull request closed without merging**
