### PR TITLE
more types extension

### PR DESCRIPTION
**Pull request by lego7set**
it adds 7 new types: object, array, set, map, symbol, nothing, and function (ignore the regexp type i was going to make).

before you say that json and object extensions exists, i have to say that these values are compiled, and are passed by reference instead of value.

please merge.

also tell me if there are any errors or anything i should add.

### CODE REVIEW

**Comment by mariocraft987** [comment]
Surely get added 👍

**Comment by mariocraft987** [comment]
https://community-extensions.vercel.app/

**Comment by lego7set** [comment]
nice

**Comment by RedMan13** [comment]
I don't see how passing an id to the object is faster then the objects extension which literally passes the whole objects instead of reparsing everything like the json extension does

**Comment by RedMan13** [comment]
also should be noted: as this isnt meant to be used in turbowarp there is an entire set of APIs built into pm specifically for custom values that can be used here to implement custom renders in monitors snd reporters and also ensure that when parsing/serializing the values get put into existence 
and to be clear I do not mean this needs to changed, just that this can be done instead if desired as the systems do exist

**Comment by lego7set** [comment]
wait there's an entire set of API's for that? i thought my objects were just getting stringified? also they arent ids thrown around, more like literal javascript objects and generator functions cuz i used the compiler.

**Comment by RedMan13** [comment]
no, the objects extension literally just extends the map class to setup some helper functions and a custom stringify function then using that custom map class directly without regeneration

**Comment by RedMan13** [comment]
sorry I missread

**Comment by RedMan13** [comment]
but, on a completely rewriten note that is literally what the object extension does too, as return values aren't casted in any way

also I'ma like actually fully review this in a bit to merge cause :trollface:

**Comment by RedMan13** [comment]
yeah this looks good to me

**Comment by lego7set** [comment]
nice.

**Comment by mariocraft987** [comment]
It does not work!!: https://studio.penguinmod.com/editor.html?extension=https://extensions.penguinmod.com/extensions/VeryGoodScratch42/More-Types.js

**Pull request merged**
