### PR TITLE
Better Input Extension

### PR DESCRIPTION
**Pull request by SharkPool-SP**
A remodeled "Ask () and wait" block extension that is FULLY customizable! (Uses CSS)

You can add buttons, inputs, dropdowns, sliders, effects, images, and more!!!

Screenshot 2023-08-07 204844

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
Thumbnail:

257149288-c4a74de2-08a5-4ca2-a2b1-e434031dd0d9

**Comment by RedMan13** [comment]
you didnt add your extension to the extension list?

**Comment by SharkPool-SP** [comment]
> you didnt add your extension to the extension list?

which one?

**Comment by RedMan13** [comment]
theres only one here?

**Comment by SharkPool-SP** [comment]
> theres only one here?

wdym "theres only one here"?

**Comment by RedMan13** [comment]
> > theres only one here?
> 
> wdym "theres only one here"?

there is only one extension in this pr

**Comment by JeremyGamer13** [comment]
ill add the extension myself since i havent added instructions on how to add it yet

**Comment by RedMan13** [comment]
> ill add the extension myself since i havent added instructions on how to add it yet

i thought thats what all the steps inside the readme are for

**Comment by Ianyourgod** [comment]
i get the error: "vm Unexpected input recieved in replaceUnsafeChars".
Can you fix that? I'll try to find the cause.

**Comment by Ianyourgod** [comment]
this also happens in tw so its most likely a problem with your extension

**Comment by RedMan13** [comment]
> ill add the extension myself since i havent added instructions on how to add it yet

i thought thats what the steps in the readme where for

**Comment by RedMan13** [comment]
wth, why didnt github update

**Comment by SharkPool-SP** [comment]
> > > theres only one here?
> > 
> > 
> > wdym "theres only one here"?
> 
> there is only one extension in this pr

Because I only pr-ed one extension

**Comment by SharkPool-SP** [comment]
> i get the error: "vm Unexpected input recieved in replaceUnsafeChars".
> Can you fix that? I'll try to find the cause.

Yea i got that error too. Idk why lmao. It’s not a big deal at the moment since the extension and all blocks works as intended

**Comment by KyleKart** [comment]
my brain hurts

**Comment by SharkPool-SP** [comment]
> > > > > theres only one here?
> > > > 
> > > > 
> > > > wdym "theres only one here"?
> > > 
> > > 
> > > there is only one extension in this pr
> > 
> > 
> > Because I only pr-ed one extension
> 
> thats the one im refering to?

I pr-ed this on turbowarp and penguinmod

**Comment by SharkPool-SP** [comment]
> i get the error: "vm Unexpected input recieved in replaceUnsafeChars". Can you fix that? I'll try to find the cause.

Ok I figured out the cause for the 'error'. I noticed alot of other merged extensions face the same error. Its not harmful btw. Basically, (for this extension) since everything (most importantly text) is customizable the console is scared that the user will write malicious stuff (even though its impossible) and automatically replaces unsafe characters with safe ones. Its not something to worry about :)

**Comment by RedMan13** [comment]
> > > > i get the error: "vm Unexpected input recieved in replaceUnsafeChars". Can you fix that? I'll try to find the cause.
> > > 
> > > 
> > > Ok I figured out the cause for the 'error'. I noticed alot of other merged extensions face the same error. Its not harmful btw. Basically, (for this extension) since everything (most importantly text) is customizable the console is scared that the user will write malicious stuff (even though its impossible) and automatically replaces unsafe characters with safe ones. Its not something to worry about :)
> > 
> > 
> > you have no idea about what your talking about do you...
> 
> I do? I prolly explained it wrong… 😑

unless what you where trying to say is that its throwing an error because color2 isnt defined (which can be ignored safely)
you dont actually know what your talking about

**Comment by SharkPool-SP** [comment]
> 

Oh you’re right. I thought it was a different error… I mean the reason why I said that explanation is because what I read online. I’ll fix it in a future update when I add stuff. Shouldn’t be long

**Comment by RedMan13** [comment]
no need to fix it as the internal fix to make the error go away has already been built and deployed

**Comment by SharkPool-SP** [comment]
> no need to fix it as the internal fix to make the error go away has already been built and deployed

Oh ok 👍

**Comment by SharkPool-SP** [comment]
Updated! Added  a bunch more stuff

**Comment by JeremyGamer13** [comment]
i forgor i need to fix an incompatibility for this

**Comment by SharkPool-SP** [comment]
> i forgor i need to fix an incompatibility for this

What do you mean?

**Comment by JeremyGamer13** [comment]
in PM color inputs return different values
i need to fix that since its easier to just match TW where it returns a hex color

**Comment by SharkPool-SP** [comment]
> in PM color inputs return different values
> i need to fix that since its easier to just match TW where it returns a hex color

Really? What does it report?

**Comment by JeremyGamer13** [comment]
i just fixed it now but previously it reported the decimal color value

**Comment by JeremyGamer13** [comment]
also this extension looks good to be merged, may not appear on the website for a bit since im gonna update the site

**Pull request merged**
