### PR TITLE
Create CockatielLocation.js

### PR DESCRIPTION
**Pull request by bruhbeast-pixel**
**A location extension with a lot of reporters.**
_Here is the blocks:_
image
_Image is here:_
image
V2. It was kind of quirky (sorry SharkPool) but 99% of that, it's fine!
The image is kind of low quality, sorry for that!

### CODE REVIEW

**Comment by SharkPool-SP** [comment]
the name of the extension should contain the theme of the extension. Also wrap your extension in `function(Scratch)` like the other extensions.

Also also use `Scratch.fetch()` instead of fetch()

**Comment by SharkPool-SP** [comment]
One more thing, ill need the svg of the thumbnail

**Comment by bruhbeast-pixel** [comment]
> One more thing, ill need the svg of the thumbnail

CockatielLocation
You may fix the code, I accidentally ruined it a bit ._.

**Comment by SharkPool-SP** [comment]
You didn't need to edit that, I wasn't done. image

**Pull request merged**
