### PR TITLE
Create Box2D Physics extension (with joints and springs)

### PR DESCRIPTION
**Pull request by pooiod**
Physics with joints and springs for penguinmod
image
[example project](https://studio.penguinmod.com/#6201978047161)

### CODE REVIEW

**Comment by RedMan13** [comment]
menguin pog

**Comment by RedMan13** [comment]
why cant the code jus tbe inside the function????

**Comment by RedMan13** [comment]
arlso erm like you shouldnt import modules and should build them into the extension beaseu erm uh erm the packager existst

**Comment by RedMan13** [comment]
image

**Comment by pooiod** [comment]
I had to do some funky stuff to get the extension to work, and to not crash my code editor

**Comment by RedMan13** [comment]
bleh

**Comment by pooiod** [comment]
I put everything inside of the function

**Comment by RedMan13** [comment]
i think there should be gaps in the category? so that each set of blocks is seperate
but either way, i made the penguin into a tire!!!
[Screen recording 2024-02-14 6.53.55 AM.webm](https://github.com/PenguinMod/PenguinMod-ExtensionsGallery/assets/74981904/5f269b5a-d9e4-455e-b9e8-10df34138fc9)

**Comment by nmsderp** [comment]
This seems like a way better alternative to Box2D by griffpatch. This would allow for some really cool projects. I think this should be merged.

**Comment by cubers93** [comment]
should have included gliding physics (like learn to fly)

**Comment by pooiod** [comment]
I'm not sure how to do that, since this is already held together with duct tape, but I can try

**Comment by pooiod** [comment]
what do I do if I want to edit my extension?

**Comment by JeremyGamer13** [comment]
i think github needs you to make a new PR to edit it again

**Comment by pooiod** [comment]
ok

**Pull request merged**
