### PR TITLE
added Penguin Console extension

### PR DESCRIPTION
**Pull request by JustablockCode**
so i added penguin console extension that was made by me:))

### CODE REVIEW

**Comment by JustablockCode** [comment]
why isn't the extension documentation button shown?

**Comment by RedMan13** [comment]
the bleh

**Comment by JustablockCode** [comment]
> the bleh

wdym

**Comment by JustablockCode** [comment]
bruh

**Comment by JustablockCode** [comment]
ok now?

**Comment by JustablockCode** [comment]
aww man

**Comment by mariocraft987** [comment]
https://turbowarp.org/editor?extension=https://extensions.turbowarp.org/-SIPC-/consoles.js

**Pull request closed without merging**
