### PR TITLE
version 1.7

### PR DESCRIPTION
**Pull request by mariocraft987**
Fixed a bunch of changes

### CODE REVIEW

**Comment by mariocraft987** [comment]
Yes

**Comment by SharkPool-SP** [comment]
> @RedMan13, for the original pr of this, did you even look at this before merging

He did not. So much formatting problems, and now we're stuck doing this

**Comment by RedMan13** [comment]
,

**Comment by RedMan13** [comment]
I don't understand I'm pretty sure this was rejected

**Comment by RedMan13** [comment]
oh yeah this one, tbh it was just merged as a joke extension I didntrlly care if it worked at the time :trollface:

**Comment by SharkPool-SP** [comment]
> oh yeah this one, tbh it was just merged as a joke extension I didntrlly care if it worked at the time :trollface: 

This is a penguinmod developer people 💀

**Comment by RedMan13** [comment]
and what's wrong about it :trollface:

**Comment by RedMan13** [comment]
oh no this needs to be merged unless it's changes where implemented

**Comment by mariocraft987** [comment]
uhhh..

**Pull request merged**
