### PR TITLE
Minor Animations Update

### PR DESCRIPTION
**Pull request by SharkPool-SP**
Simplifies Code + Adds a "Play animation and wait" block

### CODE REVIEW

**Comment by WAYLIVES** [comment]
How can I view your extension?

**Comment by SharkPool-SP** [comment]
> How can I view your extension?

copy the raw code and paste it into the editor

**Comment by WAYLIVES** [comment]
> > How can I view your extension?
> 
> copy the raw code and paste it into the editor

I copy and paste, but nothing opens :(

**Comment by SharkPool-SP** [comment]
> > > How can I view your extension?
> > 
> > 
> > copy the raw code and paste it into the editor
> 
> I copy and paste, but nothing opens :(

did you run it unsandboxed

**Comment by WAYLIVES** [comment]
> > > > How can I view your extension?
> > > 
> > > 
> > > copy the raw code and paste it into the editor
> > 
> > 
> > I copy and paste, but nothing opens :(
> 
> did you run it unsandboxed

изображение

# YES

**Comment by SharkPool-SP** [comment]
> > > > > How can I view your extension?
> > > > 
> > > > 
> > > > copy the raw code and paste it into the editor
> > > 
> > > 
> > > I copy and paste, but nothing opens :(
> > 
> > 
> > did you run it unsandboxed
> 
> изображение
> 
> # YES

you have to press the checkbox to run it unsandboxed :trollface:

**Comment by WAYLIVES** [comment]
> > > > > > How can I view your extension?
> > > > > 
> > > > > 
> > > > > copy the raw code and paste it into the editor
> > > > 
> > > > 
> > > > I copy and paste, but nothing opens :(
> > > 
> > > 
> > > did you run it unsandboxed
> > 
> > 
> > изображение
> > # YES
> 
> you have to press the checkbox to run it unsandboxed :trollface:

изображение
изображение

everything equal doesn't work :(

**Comment by SharkPool-SP** [comment]
> > > > > > > How can I view your extension?
> > > > > > 
> > > > > > 
> > > > > > copy the raw code and paste it into the editor
> > > > > 
> > > > > 
> > > > > I copy and paste, but nothing opens :(
> > > > 
> > > > 
> > > > did you run it unsandboxed
> > > 
> > > 
> > > изображение
> > > # YES
> > 
> > 
> > you have to press the checkbox to run it unsandboxed :trollface:
> 
> изображение изображение
> 
> everything equal doesn't work :(

reload the page and then try again

**Comment by WAYLIVES** [comment]
> > > > > > > > How can I view your extension?
> > > > > > > 
> > > > > > > 
> > > > > > > copy the raw code and paste it into the editor
> > > > > > 
> > > > > > 
> > > > > > I copy and paste, but nothing opens :(
> > > > > 
> > > > > 
> > > > > did you run it unsandboxed
> > > > 
> > > > 
> > > > изображение
> > > > # YES
> > > 
> > > 
> > > you have to press the checkbox to run it unsandboxed :trollface:
> > 
> > 
> > изображение изображение
> > everything equal doesn't work :(
> 
> reload the page and then try again

изображение

# THAAANK YOUU!!! :trollface:

**Comment by SharkPool-SP** [comment]
> > > > > > > > > How can I view your extension?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > copy the raw code and paste it into the editor
> > > > > > > 
> > > > > > > 
> > > > > > > I copy and paste, but nothing opens :(
> > > > > > 
> > > > > > 
> > > > > > did you run it unsandboxed
> > > > > 
> > > > > 
> > > > > изображение
> > > > > # YES
> > > > 
> > > > 
> > > > you have to press the checkbox to run it unsandboxed :trollface:
> > > 
> > > 
> > > изображение изображение
> > > everything equal doesn't work :(
> > 
> > 
> > reload the page and then try again
> 
> изображение
> 
> # THAAANK YOUU!!! :trollface:

np

**Pull request merged**
